### ISSUE TITLE
WIX project build stopped to work on build agent after update to Windows 10 - 1607

### ISSUE THREAD

**Issue by RobertK66** [jozefizso/WiX.Toolset.NuGet#1]
I used your "Nuget Package Only"-solution to build my 2 Installer projects without problems until now. It now stopped working after my build agent machine did the 'aniversary Update' to 1607. The build still runs on my developer machine, but there I also have the WIX Toolset installed in my VS.

Error on build agent:

> The "ResolveWixReferences" task could not be loaded from the assembly ...packages\WiX.Toolset.UnofficialFork.3.10.3\tools\wix\WixTasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

Versions used on Dev Client: Win10 - 1607 / Visual Studio 2015 Update 3 / WIX Toolset 3.10.2.2516,
on Build Agent Win10 - 1607 / Visual Studio 2015 Update 2 / no Wix Toolset installed 
Nuget Package used up to now : 3.10.2 

What I tried: I installed Wix Toolset (3.10.3) on build agent -> no change (build also fails in VS)
I upgraded the WIX nuget package in the solution to 3.10.3 -> no change

Any advice where to look for a solution of this problem !? (I am not very familiar with the WIX tool-chain and how to use it by hand - that's the reason I used your package ;-) )

I am going to upgrade VS to Update 3 on the build machine in case this makes any differnece....

**Comment by jozefizso** [comment]
Some people already had issues with **Microsoft.Build.Utilities.dll** could not be found on some Windows 10 system. See [Cannot build WIX project on windows 10](http://stackoverflow.com/questions/35132076/cannot-build-wix-project-on-windows-10)

Do you have .NET Framework 2.0/3.5 Feature enabled on your Build Agent machine?

`Microsoft.Build.Utilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` assembly is distributed as part of .NET Framework 2.0 - it's not part of Visual Studio until MSBuild 14.

**Comment by RobertK66** [comment]
Ok, the feature net 3.5 is not enabled! 
But the build worked prior to 1607 Upgrade in Windows 10 (did it disable this !?)  !?
I will test if this helps once the VS Update 3 install is finished .....

**Comment by jozefizso** [comment]
Personally I have the same developer machine setup as your reported Dev Client.

We haven't upgraded our build agent machine to Windows 10 1607. We have VS 2015 Update 3 though. And we don't have .NET 3.5 enable on it, just 4.6.

**Comment by jozefizso** [comment]
I have .NET 3.5 installed on my developer machine.

**Comment by jozefizso** [comment]
This may explain why .NET can reference MSBuild Tasks 2.0 on some machines without .NET 3.5 https://github.com/wixtoolset/issues/issues/3872#issuecomment-166097628

**Comment by RobertK66** [comment]
OK, for the records:
1.) Upgrade to VS 2015 Update 3 and reboot build agent -> no change.
2.) Enabled "Windows feature .Net 3.5" -> yeah !!  this worked! The build now runs (again).
BTW: on my dev machine this feature is/was also enabled. Why this is needed now on build agent also is beyond my understanding but I am happy it works again :-)

Thx. a lot for your fast and helpful replies!

**Comment by jozefizso** [comment]
As mentioned in wixtoolset repository, this may be caused by assembly redirection policy. Some application might have modified system redirection policy and it was reset by upgrade to 1607.
