### ISSUE TITLE
Why are there 3 WiX.Toolset packages ?

### ISSUE THREAD

**Issue by robdalsanto** [jozefizso/WiX.Toolset.NuGet#4]
Surely we don't need:

- [WiX.Toolset](https://github.com/akoeplinger/WiX.Toolset.NuGethttps://github.com/akoeplinger/WiX.Toolset.NuGet) (v3.9),
- [WiX.Toolset.2015](https://github.com/shana/WiX.Toolset.NuGet) (v3.10)
- [WiX.Toolset.UnofficialFork](https://github.com/jozefizso/WiX.Toolset.NuGet) (v3.11)

**Comment by jozefizso** [comment]
For some projects, you will get many forks.

I can speak only for this one. I maintain the 3.10, 3.10-patched and 3.11 WiX releases here.
Others exist for historical reasons.
