### ISSUE TITLE
Clarification on LICENSE

### ISSUE THREAD

**Issue by ariel11** [jozefizso/WiX.Toolset.NuGet#5]
Hello,

I work on a project called "ClearlyDefined," which is a database of licensing information for open source components.  I help verify that license info for various components/packages. 

There is a discussion around whether the main, overall license for these NuGet packages is the MS-RL or MIT (https://github.com/clearlydefined/curated-data/pull/7491). 

Can you confirm if the MIT license only applies to the code used to build the NuGet package?  While the NuGet package itself is MS-RL licensed?  Is that how you see the licensing?

Thanks

**Comment by jozefizso** [comment]
The NuGet package and content is under MS-RL license.

Code used to build this package is under MIT.

**Comment by ariel11** [comment]
Thanks so much!
